- README.md
Added Wuthering Heights by Emily Bronte along with Goodreads link.
> Add Wuthering Heights by Emily Bronte

- README.md
Adding Surely You're Joking, Mr. Feynman!: Adventures of a Curious Character by Richard Feynman under biographies. He is an inspiring person.
> Adding Surely you're joking Mr feynman

- README.md
Added Jonathan Livingston Seagull by Richard Bach to Philosophy and Psychology
This is a story for people who follow their dreams and make their own rules .
It is a fable about the importance of making the most of our lives , even if our goals run contrary to the norms of our flock,tribe or neighbourhood.
Through the metaphor of flight , Jonathan's story shows us that , if we follow our dreams , we too can soar.
> Addition to Philosophy and Psychology

- README.md
Convict Conditioning by Paul Wade explains simple "old-school" calisthenics in an interesting way .
This books is one of the most interesting yet amazingly effective books on health which stresses on simple training routines utilising no specialised gym equipment and only one's body weight.
> Added Convict Conditioning in Health Section

- README.md
New Book added:
[Man's Search for Meaning](https://www.goodreads.com/book/show/4069.Man_s_Search_for_Meaning) by Viktor E. Frankl
This book has deep spiritual meaning and can be added to the great list that you have already created.
> Added Man's Search For Meaning

- README.md
[Awaken the Giant Within: How to Take Immediate Control of Your Mental, Emotional, Physical and Financial Destiny!](https://www.goodreads.com/book/show/180116.Awaken_the_Giant_Within) by Anthony Robbins
Great philosophical book.
> Added Book: Awaken the Giant Within

- README.md
This book has good insights. Read some interesting comparisons about the history of countries.
> Added 23 Things They Don't Tell You About Capitalism

- README.md
[Goodreads Link](http://www.goodreads.com/book/show/17342664-business-sutra)
This book presents a very Indian approach to management science which is subjective in nature as compared to the western view of management which is objective in nature. The author takes up various Indian mythological stories and links them to contemporary business situations/ cases.
> Add Business Sutra : A Very Indian Approach to Management

- README.md
> Added a book

- README.md
These have certainly blown my mind. I've read all of them multiple times over my lifetime.
> A couple of fiction classics

- README.md
Let's read something fantastic!! 
Happy hacktoberfest :P
> #29 Fantasy books added. 

- README.md
Extracted economics books and created new genre.
> Fix for issue #39

- README.md
Just a couple of typos I found.
> Fix typos in Fantasy

- README.md
this is a spanish novel which covers the first years of the XXth century and also tells the story of a woman who lived in that years. I think it should be included because it describes the society of that time and how Spain was affected by the civil and world's 1st war.
> added El tiempo entre costuras

- README.md
And the book **Learn You a Haskell for Great Good!** There's no any category for Computer Science and Programming, so I added to README to add more books related with these themes. Also I added the book **Learn You a Haskell for Great Good!** because Haskell it's a very powerful programming language to solve problems, specially recursive problems, and not very people know this language. Also, this books it's a very good starting point to start to program with Haskell becaues it's very well explained and it's very funny!
> Add it Computer Science and Programming category

- README.md
Separated classics into it's own subcategory & added a couple of new entries (His Dark Materials and Adventures of Huckleberry Finn).
> separate classics from others category

- README.md
I sorted the books according to the top genres on GoodReads. Not sure what alphabetizing convention was being used, so I left that undone for now, but could easily alphabetize by author or title if needed.
> Added subcategories for Fiction and sorted all books under "Others"

- README.md
Added authors of the following books:
* Catch 22
* His Dark Materials
* Foundation
* Dune Chronicles
> Add missing author names to the books 

- README.md
Added 3 books in the genre _horror_ in the **fiction** category.
Referencing issue #38 and #29
> Add horror genre in fiction category | Hacktoberfest

- README.md
Added The Ethical Slut: A Guide to Infinite Sexual Possibilities to the sexuality field.
This is a book about sexuality and different kinds of relationships that we could have and experiment with. It's really interesting and it open your mind to a new world.
> Added The Ethical Slut: A Guide to Infinite Sexual Possibilities

- README.md
> Added Crime and Punishment

- README.md
> added Orson Scott Card to Ender's Game

- README.md
PR for issue #29. I'd like to add the Dark Tower series to the Fantasy section because, even though it might take some time to read (it's 7 volumes + an additional shorter one), it's one of the fantasy works I enjoyed the most. It subtly lays down a few basic "rules" throughout the story and, once you accept those, everything flows really well and you can be taken through an amazing variety of settings.
> Add the Dark Tower series to the Fantasy section

- README.md
Added Mikhail Bulgakov 'The Master and Margarita'
> Add Mikhail Bulgakov 'The Master and Margarita'

- README.md
Added books according to Issue #29
> Added "Memory Man" and "The Girl on the Train"

- README.md
> Add Historical Fiction Book

- README.md
This is a great book exploring the implications of nanotechnology.
> Add "The Diamond Age"

- README.md
http://www.goodreads.com/book/show/971936.Spycraft
Excellent book to understand the world of espionage and the tools used to spy
> Adding Spycraft to list of books

- README.md
Added Andy Grove's book High Output Management, the quintessential leadership must-read.
> Add Andy Grove's book High Output Management

- README.md
http://www.goodreads.com/book/show/10256723-ghost-in-the-wires Kevin Mitnick was the most elusive computer break-in artist in history; a high tempo, thrilling read. Should be required reading for all would-be CISOs! ;)
> adding autobiography by kevin mitnick

- README.md
the director by david ignatius
http://www.goodreads.com/book/show/23316525-the-director  CIA Director goes to DEFCON  - a convincing fictional cyber espionage thriller
> Adding Fiction Book

- README.md
Added "A Mind for Numbers: How to Excel at Math and Science (Even If You Flunked Algebra)" by Barbara Oakley to the Logic and Problem Solving Section. Reference Issuse #29.
> Add A Mind For Numbers to Logic&PS

- README.md
Kingpin by Kevin Poulson - expose of the construction and takedown of one of the worlds largest cybercrime forums ~ a trip down the rabbit hole for any reader curious about the mechanics and culture surrounding credit card theft (http://www.goodreads.com/book/show/9319468-kingpin)
> Adding historic non-fiction title

- README.md
Why should we bother fighting ego in an era that glorifies social media, reality TV, and other forms of shameless self-promotion?  Armed with the lessons in this book, as Holiday writes, “you will be less invested in the story you tell about your own specialness, and as a result, you will be liberated to accomplish the world-changing work you’ve set out to achieve.”
> Add Ego Is the Enemy to Philosophy and Psychology

- README.md
It is used as the textbook for algorithms courses at many universities and is commonly cited as a reference for algorithms in published papers, with over 8900 citations documented. The book sold half a million copies during its first 20 years. Its fame has led to the common use of the abbreviation "CLRS" (Cormen, Leiserson, Rivest, Stein).
This title covers a broad range of algorithms in depth, yet makes their design and analysis accessible to all levels of readers. Each chapter is relatively self-contained and can be used as a unit of study. The algorithms are described in English and in a pseudocode designed to be readable by anyone who has done a little programming. The explanations have been kept elementary without sacrificing depth of coverage or mathematical rigor.
> Add Introduction to Algorithms to Computer Science and Programming

- README.md
This book is Freakonomics#1. Freakonomics#2 titled SuperFreakonomics has already been included in the list.
Which is more dangerous, a gun or a swimming pool? What do schoolteachers and sumo wrestlers have in common? Why do drug dealers still live with their moms? How much do parents really matter? How did the legalization of abortion affect the rate of violent crime?
> Add Freakonomics to Startups and Business

- README.md
Part memoir, part master class by one of the bestselling authors of all time, this superb volume is a revealing and practical view of the writer's craft, comprising the basic tools of the trade every writer must have.
Brilliantly structured, friendly and inspiring, On Writing will empower and entertain everyone who reads it—fans, writers, and anyone who loves a great story well told.
> Add On Writing: A Memoir of the Craft to Writing

- README.md
Losing My Virginity is the unusual, frequently outrageous autobiography of one of the great business geniuses of our time. When Richard Branson started his first business, he and his friends decided that "since we're complete virgins at business, let's call it just that: Virgin." Since then, Branson has written his own "rules" for success, creating a group of companies with a global presence, but no central headquarters, no management hierarchy, and minimal bureaucracy.
> Add Losing My Virginity to Autobiographies and Biographies

- README.md
Hi, I updated the formatting to match GitHub's markdown.
- The table of contents links work properly
- The headers render properly
I also added a book to the philosophy & psych section that focuses on grit/resilience and how it ties into success.
> Update formatting & add book

- README.md
* Fix broken links for several books
> Fix markup issues

- README.md
Added under history - it truly is a mind expanding book :)
> Added Sapiens: A Brief History of Humankind

- README.md
I believe this book deserves to be on the list because it is a fantastic treatment of an under-covered topic, self control. It presents an interesting angle, with a psychologist and a science-writer teaming up to deliver this excellent treatment.
> adding Willpower

- README.md
https://dl.acm.org/citation.cfm?id=539932
And won the Pulitzer in 1980: http://www.pulitzer.org/winners/douglas-r-hofstadter
> Godel, Escher, Bach was first published in 1979

- README.md
Fun exploration of the mind and of Timothy Leary's 8-circuit model. Basically a collection of ideas and thought experiments that the author suggests you try and see how you feel
> Add Prometheus Rising - Robert Anton Wilson

- README.md
Cory Doctorow's Little Brother will make you remember that you're constantly being watched. In the book, the interesting ways in which the "little brother" evades the "big brother"'s control are fun and witty. Definitely a good read. Cheers.
> Add Little Brother to Science Fiction

- README.md
Set in an alternate future where North America has become one state and Quebecois radicals want to secede, the action happens at a tennis academy and a nearby halfway house in Boston, Massachusetts, this book will expand your mind with a mere attempt to read it. It's brilliant, funny, and sad, but it's also packed with interesting ideas about entertainment, addiction, self-development, being human, the civic ideal, setting and meeting expectations, family, and a whole lot more. It's also got tons of footnotes and plenty of fascinating factual asides about pharmacology, tennis, Alcoholics Anonymous, and much more.
> Add Infinite Jest

- README.md
Hey there!
A great initiative.Here is my contribution to it.
_Changes made_
I have added the book **Mindset: The new psychology of success** by **Carol S. Dweck,Ph.D.** under the **Philosophy and Psychology** section.
_Why this book?_
I have read this book over & over again and yet I'm amazed by it everytime.You go through the pages you realise this are the mistakes you have been making over and over again.But why do a lot of people commit these mistakes? The author presents this in a very elegant and fresh concept of different mindsets: the growth mindset and the fixed minset.The author goes onto presents the findings and with each one you realise that you should have known it sooner!
Let me know if you want more from me.
Thanks and have a good day!
> Added Mindset by Carol S. Dweck

- README.md
This book covers the author, a renowned sociologist from Berkeley, and her journey into the conservative south in the US. Her journey is one about understanding the experiences and deep stories of the conservative right, especially more important at a time when American political polarization is so severe.
> Added a recent book that is on bridging political boundaries

- README.md
mainly by using google books, wikipedia, and goodreads
> Add 9 missing "Year Published"

- README.md
The book is complicated and requires focus to be understood, bit it deserves that. The author's search for Quality is rather thrilling to observe. The Quality described in the book can challenge lots of people to become more conscious about their work. Overall, great book for those who enjoy challenging reading.
> Add Zen and the Art of Motorcycle Maintenance: An Inquiry Into Values

- README.md
This is a very interesting book about obscure but interesting places to visit all over the world
> Added new section, new book

- README.md
I think this book should be read by all entrepreneurs out there running towards there passion without knowing the **"WHY"** factor for its existence towards society.
Start With Why: How Great Leaders Inspire Everyone to Take Action, is a book by Simon Sinek that appeared on The New York Times Best Seller list.
> Added - Start with Why by Simon Sinek

- README.md
It is impossible to overstate the importance of this book.
Michelle Alexander shows how slavery in the United States has not disappeared - it has just changed shape, into the mass incarceration of black men. 
The author, a former supreme court justice aid, meticulously describes and delineates the "War on Drugs" as being a system designed to 1) repress inner city lower income communities and effectively turn them into red zones, 2) place "criminals" under constant supervision and monitoring of the state, 3) prescribe harsh and unhelpful sentences for drug use and possession beyond the range of 'justice,' 4) criminalize poverty, 5) reward state and local drug enforcement agencies in the form of cash (federal subsidies for picking up and prosecuting drug criminals), and 6) effectively …
> Added: The New Jim Crow

- README.md
Under Philosophy And Psychology. A classic about meditation and positive thinking utilising own beliefs.
> Added: The Power of Now by Eckhart Tolle

- README.md
Added to Design Section. Book of compiled/random art observations over 20 year period. Great to be used as a timeless inspiration.
> Added: The Art Of Looking Sideways by Alan Fletcher

- README.md
* The book I am adding is The Brain: The Story of You
* I am adding this book to Science and Medicine section.
* I think this book deserves to be in this list because it is a good and modern introduction into the science of the brain. It is very well written and doesn't expect any background in this field. I found it very fascinating to read and had many moments were I was just stunned by the capabilities of our brains. 
* The book I am adding is Make It Stick: The Science of Successful Learning
* I am adding this book to Education section.
* I think this book deserves to be in this list because it has many tips for anyone who wants to improve his learning skills. The authors start by claiming that basically a large number …
> Add The Brain and Make It Stick

- README.md
> Adding year on some Startups and Business books

- README.md
All of his Cosmere books are amazing, and I suggest people start with "The Final Empire" - the first book of the Mistborn trilogy.
* The book I am adding is Mistborn
* I am adding this book to Fantasy section.
* I have read this book 15~ times.
* I think this book deserves to be on this list because it is the best fantasy book I read, the world building is amazing, and everyone I recommended the book to thanked me so far. The magic system is awesome and the story is captivating
> Add Mistborn by Brandon Sanderson

- README.md
Author's name is Ian MORRIS not "Morrisage"
https://www.amazon.com/Ian-Morris/e/B001IQZPSC
**If you are adding more than 1 category duplicate this section**
* The book I am removing is _ _ _ _
* I am removing this book from _ _ _ _ section.
* I think this book should not be in this list because _ _ _ _
**If you are removing more than 1 book duplicate this section.**
> Correcting author name on an entry.

- README.md
- Capitalized an author
- Added year to Jane Eyre
> capitalization + year for Jane Eyre

- README.md
* The book I am adding is Pilgrim at Tinker Creek
* I am adding this book to Nature section.
* I think this book deserves to be in this list because:
Really wonderful book about nature, the passage of time, and really paying attention to the world around you. The whole book could almost be categorized as prose poetry; it's not a large volume but took me a while to get through just due to the sheer density of lush and sensitive description. It chronicles a year in which both nothing and everything seems to happen; Dillard mostly hangs out around her home and its backyard creek (or at least, the book is constrained mostly to these experiences) but manages to evoke transcendent beauty and spirituality, capturing cycles of predator and prey, weather, and her …
> Added "Pilgrim at Tinker Creek"

- README.md
* The book I am adding is The Immortal Life on Henrietta Lacks.
* I am adding this book to Autobiographies and Biographies section (although could also be in Health category).
* I have read this book one time and I recommended it to all my friends.
* I think this book deserves to be in this list because it tells the moving story of a woman who contributed to science without her knowledge, it teaches lessons about health ethics and it received many literary awards.
> Added The Immortal Life of Henrietta Lacks

- README.md
* The book I am adding is The Man Who Knew Infinity.
* I am adding this book to Autobiographies & Biographies section.
* I have read this book 5 times.
* I think this book deserves to be in this list because it gives a detailed account of the life of renowned mathematician, Ramanujan. This book inspires every single person to achieve greatness on the grounds of humbleness, determination and passion to strive forth. This book is a must-read.
> [Added] A book in the Autobiographies & Biographies Section.

- README.md
* The book I am adding is Le Ton beau de Marot: In Praise of the Music of Language
* I am adding this book to Language section.
* I think this book deserves to be in this list because:
An incredible book about the art of translation, and a million other very welcome tangents. Hofstadter spins endless threads of ideas around a fascinating central premise: that a specific favorite poem of his, by a fairly obscure 16th century French poet, can spark an infinite variety of translations. There are 80+ of these translations sprinkled throughout the book, from friends and family, students and colleagues, noted translators and computer programs (and many by Hofstadter himself). Among them, a feast of academic lessons and personal reflections interwoven into a …
> Added "Le Ton beau de Marot"

- README.md
Fixed order per https://github.com/hackerkid/Mind-Expanding-Books/pull/154
> Added Bolo'bolo (fixed order)

- README.md
Fixed order per https://github.com/hackerkid/Mind-Expanding-Books/pull/153
> Added "Origins of Form" (fixed order)

- README.md
Fixed order per https://github.com/hackerkid/Mind-Expanding-Books/pull/152
> Added "Cosmicomics" (fixed order)

- README.md
* The book I am adding is Einstein: His Life and Universe
* I am adding this book to  Autobiographies and Biographies section.
* I have read this book  1 times.
* I think this book deserves to be in this list because 
> It is a really inspiring book about the life and the ideas of one the most famous physics ever. The thing I appreciated the most is how it tells you about how the scientist started thinking about those concepts which have changed our understanding of the world
> Added Einstein biography by Isaacson

- README.md
* The book I am adding is  Outwitting the Devil
* I am adding this book to Business section.
* I think this book deserves to be in this list because this book covers the elements one needs for success in a dialog between Hill and the Devil himself. This is a unique approach to understanding how our minds work in shaping our reality. This book was not published at the time of writing for reasons outlined in the introduction by Sharon Lechter; that being the consternation behind communicating with the Devil. This compels me to request it be added to the Mind expanding book list
* The book I am adding is  Think and Grow Rich
* I am adding this book to Business section.
* I think this book deserves to be in this list because …
> natac13 added 2 Napoleon Hill books

- README.md
* The book I am adding is  Atlas Shrugged by Ayn Rand
* I am adding this book to Fiction/Classics section.
* I think this book deserves to be in this list because this book is highly controversial! This book, whether you are inline with the concepts or not, will definitely expand your thoughts from the common narrative in today's society.
> natac13 added Atlas Shrugged by Ayn Rand to Fiction/Classics

- README.md
* The book I am adding is The Martian
* I think this book deserves to be in this list because it is a very highly rated book on Goodreads, was very well received and has had a film adaptation.
> Add The Martian to Science Fiction

- README.md
* The book I am adding is Atomic Habits by James Clear
* I am adding this book to Philosophy and Psychology  section.
* I think this book deserves to be in this list because you a clear gist of things which queues in our daily routine triggers habit formation. It also roots into path of less resistance to create clutter free environment. Breaking down book into four laws and other additional material on website such as cheat-sheet can make it more than just another self help book.
> Add Atomic Habits

- README.md
* The book I am adding is 1984
* I am adding this book to Classics section.
* I think this book deserves to be in this list because the dystopian society described in the book feels increasingly familiar to us as the years pass on.  A world in which the government is always listening in, and high-tech devices can eavesdrop in people’s homes (Hey, Alexa, what’s up?); the government is also able to forge historical facts in the name of national security, etc. This book displays the importance of critical thinking and good judgement, as George Orwell's haunting writing paints a depressive world in which Winston Smith, an everyman for his times, silently protests against the government in his own way.
Even as society evolves, the divisiveness of human factions …
> add George Orwell's 1984 to Classics

- README.md
A roller-coaster ride through the unpredictable, exciting, and challenging universe of computers, games, puzzles, mazes, and computer art. "Pickover's dazzling array of tortuous mind-benders and arcane minutiae delights and surprises. It's easy to get trapped in his enticing labyrinth of seductive mind games".--Science News.
* The book I am adding is Mazes of the Mind
* I am adding this book to Logic and Puzzles section.
* I have read this book several times.
* I think this book deserves to be in this list because it really explores the world of logic and the mind
* The book I am adding is The Art of Deception
* I am adding this book to Politics section.
* I think this book deserves to be in this list because it provides a fascinating perspective in …
> Excellent exploration of the mind across different perspectives

- README.md
* The book I am adding is _How the Internet Happened_ by Brian McCullough
* I am adding this book to the History section.
* I think this book deserves to be on this list because it details a time that completely changed technology as a whole, and made the world connected in an unforeseen way, of which is making even this pull request possible.
> Add new book: How the Internet Happened by Brian McCullough

- app/package-lock.json
- app/package.json
- app/src/components/bookcard.js
I added the Year and Star Ratings display on the bookcard component
> Year ratings

- app/src/components/bookcard.js
- app/src/components/header.js
- app/src/components/layout.js
- app/src/pages/index.js
React was giving a few common console errors on load, so I fixed the issues I saw:
* update standard HTML class attribute to react className
* remove unused imports
* fix the key warning by adding the book.id key to the <Bookcard /> component declaration (rather than inside the bookcard.js template)
> React error fixes

- README.md
* The book I am adding is Illusions: The Adventures of a Reluctant Messiah by Richard Bach
* I am adding this book to Philosophy And Psychology section.
* I have read this book 4 times.
* I think this book deserves to be in this list because it is really cool how can open your mind to new realities, I read this book when I was fourteen the first time and It gave me the gift of start thinking deeper about all the thing I knew to that age. I loved it and I still come back to read it sometimes as it also have really good quotes. I hope anyone can enjoy this book as I did it.
> Adds the book Illusions by Richard Bach

- app/src/components/bookcard.js
Noticed a wrong "class" attribute in BookCard
> Fix css class attribute in BookCard

- app/src/components/bookcard.js
- app/src/pages/index.js
The UI of book cards was slightly refined, as described in issue #186
> Improving the UI of book cards

- README.md
* The book I am adding is "Homo Deus: A History of Tomorrow"
* I am adding this book to "History" section.
* I think this book deserves to be in this list because it is another mind expanding book from the author of "Sapiens: A Brief History of Humankind". Controversial and thought-provoking position with a lot of information inside.
> Add "Homo Deus: A History of Tomorrow"

- README.md
This book changed my perception. This is one of the best books I ever read.
> Add The third door

- README.md
This is in reference to update the rating of The third door from 4.3 to 4.28.
> Update the rating of The third Door

- README.md
* The book I am adding is Behave: The Biology of Humans at Our Best and Worst
* I am adding this book to Evolution, Science and Medicine section.
* I have read this book 1+ times.
* I think this book deserves to be in this list because it explains a lot about our brain, genetics, evolution, culture, and how it influences our behavior. The author is a neuroendocrinologist and he managed to put insane amount of information in a well structured and interesting to read format. It can be a bit complicated and also it is quite long, but I think it is worth reading for everybody. This is definitely the best science book I have ever read.
> Add Behave: The Biology of Humans at Our Best and Worst

- CONTRIBUTING.md
- README.md
* The book (series) I am adding is The Wheel of Time
* I am adding this book to the Fantasy section.
* I think this book deserves to be in this list because it's a well received high fantasy series, with great world building, engaging characters, and convincing storylines.
> Add Wheel of Time to Fiction/Fantsay

- README.md
* The book I am adding is "Happy" by Derren Brown
* I am adding this book to the Philosophy and Psychology section.
* I think this book deserves to be in this list because it's a highly rated and well-written book
> Add "Happy" to Philosophy and Psychology

- app/package-lock.json
- app/package.json
- app/src/pages/index.js
> Implemented infinite scroll

- README.md
add Mismatch: How Inclusion Shapes Design |  Kat Holmes
* The book I am adding is Mismatch: How Inclusion Shapes Design
* I am adding this book to Design section.
* I think this book deserves to be in this list because Kat Holmes really is an awesome Inclusive designer whose writing makes clear how best to design great products that work for all people
> add Mismatch: How Inclusion Shapes Design to the Design section

- README.md
added The Forever War
* The book I am adding is The Forever War
* I have read this book at least 3 times.
* I think this book deserves to be in this list because its is a deep story about the sense and nonsense of war. The author, Joe Haldeman participated in Vietnam War and processed with the book his experiences as a soldier. He puts this in an exciting and also thoughtful science fiction story. With his book he won multiple awards, like the the Nebula Award in 1975 and the Hugo and Locus awards in 1976.
> adding The Forver War by Joe Haldeman

- README.md
* The book I am adding is Utilitarianism
* I am adding this book to Philosophy And Psychology section.
* I have read this book 5 times.
* I think this book deserves to be in this list because it's a book that makes philosophy relevant using examples that are clear and give context to the complex theories it explains. It's a very easy to read book, making it all the more valuable in such a difficult field.
> Contributing books

- README.md
You can't have a list of horror books with Stephen King. 'It' will always be one of my favorite King books. The book effectively uses not only Pennywise as a horror element, but also real life threats such as Henry Bowers and his gang of school bullies and Bev's abusive father. While the book is plenty chilling, you also fall in love with the tight-knit group of misfits who are able to band together and defeat a monster that has existed since the beginning of time itself. The book is not only about monsters, but the power of friendship, which makes it so much more than your typical horror novel.
**If you are adding …
> Added It by Stephen King

- .github/PULL_REQUEST_TEMPLATE.md
Maybe this addition will help people new to open source understand better how to format their PRs.
> Added a small explanation on how to format a PR

- app/package-lock.json
- app/src/components/amazonurl.js
- app/src/components/bookcard.js
- app/src/components/categorydescription.js
- app/src/components/header.js
- app/src/components/sidebar.js
- app/src/pages/404.js
I'm not adding nor removing a book but improving site accessibility :)
> Improved accessibility according to WCAG

- app/package-lock.json
- app/src/components/feed.js
- app/src/components/sortByDropdown.js
- app/src/pages/index.js
- app/src/templates/categoryTemplate.js
regarding issue #183.
Added the sort by functionality to the feed component.
UI wise I think this pretty great but if you have something else in mind let me know.
---------
> sort by functionality issue #183

- app/src/components/feed.js
- app/src/components/sortByDropdown.js
added useMemo to prevent resorting on scroll.
added the opposite sort for each option: 
a-z
z-a
year descending/ascending
rating descending/ascending
> add useMemo and 3 more sortBy options

- README.md
* The book I am adding is And Then There Were None
* I am adding this book to Fiction (Mystery) section.
* I think this book deserves to be in this list because
- Its a beginner friendly book and still directs your complete interest
- it was published in 1939 and totally stood the test of time
- Easy language, great storyline and a super mystery. So its the combination of all the factors to make you an avid book 
reader
> Added "And Then There Were None"

- README.md
* The book I am adding is So You Want to Talk About Race
* I am adding this book to Race section.
* I think this book deserves to be in this list because discusses important topics about race, especially when white privilege and police brutality are systemic in today's racial landscape.
> Added category "race" and book title

- app/src/components/amazonurl.js
- app/src/components/bookcard.js
- app/src/components/goodreadsimage.js
This is in relation to issue https://github.com/hackerkid/Mind-Expanding-Books/issues/244.
Changes made:
* The Goodreads image has been included
* Bookcard styles have been updated
| Before | After |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/6725396/95726415-7f52b600-0cab-11eb-9724-5159a0fa642f.png) | ![image](https://user-images.githubusercontent.com/6725396/95726475-909bc280-0cab-11eb-98ca-38bda68c15f3.png) |
> Updated styles for bookcard

- app/.gitignore
added package-lock.json in gitignore file to avoid complication when merging
> added package-lock.json in gitignore file

- README.md
Added the book The Gift of Fear, a psychological and self-help book.
* The book I am adding is The Gift of Fear: Survival Signals That Protect Us from Violence
* I am adding this book to psychology  section.
* I have read this book two times.
* I think this book deserves to be in this list because it gives insight on how to understand our gut feeling and stay protected. It shows us why certain actions from other people raises alarms in our head and how to properly avoid violence in uncertain situations. The book gives deeper meaning to our instincts and when to listen to those instincts.
> Added Gift of Fear

- README.md
* The book I am adding is The Elephant in the Brain: Hidden Motives in Everyday Life 
* I am adding this book to the philosophy and psychology section.
* I think this book deserves to be in this list because it gives interesting insights into how we trick ourselves into believing we have nobler intentions than is actually the case. Given how important social signaling is and how difficult it is to fake sincerity, humans have evolved to trick themselves into thinking we have pure motives. This book explores how we deceive ourselves in many aspects of life and how we could leverage this tendency to do more good.
> Added "The Elephant in the Brain: Hidden Motives in Everyday Life"

- README.md
* The book I am adding is The Language Instinct: How the Mind Creates Language 
* I am adding this book to the language section.
* I think this book deserves to be in this list because it explains why research shows us that language is something that humans are capable of instinctually. Language is not just a feature of high general intelligence, but is a modular specific skill present in most humans.
> Added The Language Instinct: How the Mind Creates Language by Steven Pinker

- README.md
* The book I am adding is  Passions Within Reason: The Strategic Role of the Emotions 
* I am adding this book to Philosophy and Psychology section.
* I think this book deserves to be in this list because it is a interesting introduction into the subject of signaling in a social sense. It explains why it makes sense that our emotions let us make bad decisions when acting on emotions and how it helps us in the long run.
> Added Passions Within Reason: The Strategic Role of the Emotions by Robert H. Frank

- README.md
* The book I am adding is  My Inventions: The Autobiography of Nikola Tesla
* I am adding this book to the Autobiographies and Biographies section.
* I have read this book  2 times.
* I think this book deserves to be on this list because This book is about the life of a genius inventor who invents many things in his lifetime like AC, Tesla Coil,3 phase electric power According to Wikipedia"Nikola Tesla was an inventor who obtained around 300 patents[1] worldwide for his inventions".It's so incredible to look in the life of a remarkable genius how he got into this world of "Electrical engineering" and invented such things. He has mentioned so many life events as a story which are very interesting to read and be amazed by it.
> Added "My Inventions"

- README.md
* The book I am adding is "Things to Make and Do in the Fourth Dimension" by Matt Parker
* I am adding this book to Science and Medicine section.
* I think this book deserves to be in this list because it can truly motivate a person to learn mathematics. It shows the beauty of mathematical world throughout different dimensions. It has by far the best and the most humorous approach to mathematics I've ever encountered.
> Added "Things to Make and Do in the Fourth Dimension" to Science and Medicine section

- README.md
* The book I am adding is Problem Solving 101: A Simple Book
* I am adding this book to the Logic and Problem-Solving section.
* I think this book deserves to be on this list because it is very easy to understand and provides with simple yet effective tools for problem-solving.
> Added new book "Problem Solving 101" to Logic and Problem Solving Section 

- README.md
* The book I am adding is The Sixth Extinction: An Unnatural History
* I am adding this book to NATURE section.
* I have read this book one time
* I think this book deserves to be in this list because it puts us in perspective in a simple and interesting way about the impact of our race on the world we live in. It makes you open your mind about how we live.
> Added new book The Sixth Extinction: An Unnatural History

- README.md
* The book I am adding is Never Split the Difference
by Chris Voss
* I think this book deserves to be in this list because it gives great insides into situations where the mentioned negotiation techniques have worked effectively, making it an amazing book for gaining both theoretical and experimental knowledge on negotiation techniques.
> Added a book Never Split the Difference in Startups and Business

- README.md
* The book I am adding is "The Slight Edge" by Jeff Olson
* I am adding this book to Philosophy and Psychology section.
* I think this book deserves to be in this list because it has been life-changing. The premise of the book is that every small, seemingly insignificant habit, if done constantly, can lead to huge positive outcomes in life. It seems a simple concept but it motivated me in being patient and improve myself focusing on my daily actions.
> Added "The Slight Edge" to Philosophy and Psychology

- README.md
* The book I am adding is Guide to Competitive Programming: Learning and Improving Algorithms Through Contests.
* I am adding this book to the Logic and Problem Solving section.
* I think this book deserves to be in this list because as we know competitive coding is a mind sport and by doing competitive coding we increase our thinking ability and it helps the readers to increase logical ability. This book refers by my senior to increase problem-solving and logic building and it works. So, I think this book good for beginners to become experts.
> Add a book in Logic and Problem Solving

- README.md
* The book I am adding is Becoming
* I am adding this book to Autobiographies and Biographies section.
* I think this book deserves to be in this list because Becoming is the memoir of former United States first lady Michelle Obama. Described by the author as a deeply personal experience, the book talks about her roots and how she found her voice, as well as her time in the White House, her public health campaign, and her role as a mother.
> Autobiography added

- README.md
* The book I am adding is "Educated" by Tara Westover.
* I am adding this book to the Education section.
* I think this book deserves to be in this list because it provides a great perspective on the education system and how education changes people and is highly rated.
> Added Educated by Tara Westover

- app/src/components/bookcard.js
`resizeMode` prop is a `react-native` thing
> Remove react-native prop from react project (dev console error)

- app/src/components/sidebar.js
> Add react key for nav items (fix dev tools error)

- README.md
* The book I am adding is The Simple Path to Wealth: Your road map to financial independence and a rich, free life
* I am adding this book to the Economics section.
* I think this book deserves to be in this list because money is the single most powerful tool we have for navigating this complex world we’ve created, understanding it is critical. And this book does it perfectly.
> Economics book addition

- utils/README.MD
> README.md: Add info about goodreads api

- README.md
* The book I am adding is 'How Google Works' by Eric Schmidt and Jonathan Rosenberg
* I am adding this book to 'Startups and Business' section.
* I think this book deserves to be in this list because - This book gives insights on to how Google started as a small startup and how it grew so big. The way of working and first hand writing from the founders themselves is a must read for anyone and everyone interested in startups or business in general
> Add new book: How Google Works

- utils/config-sample.py
> Fix typo in sample config file

- README.md
* The book I am adding is The Ride of a Lifetime: Lessons Learned from 15 Years as CEO of the Walt Disney Company
* I think this book deserves to be in this list because in this the CEO of The Walt Disney Company shares the ideas and values he has used to reinvent one of the most beloved companies in the world and inspire the people who bring the magic to life.
> Business book addition

- README.md
* The book I am adding is  A Thousand Splendid Suns
* I am adding this book to Fiction section.
* I think this book deserves to be in this list because it shows the breathtaking story set against the volatile events of Afghanistan's last thirty years
* The book I am adding is one day in life of Ivan Denisovich
* I am adding this book to Fiction section.
* I think this book deserves to be in this list because it graphically describes protagonist struggle to maintain his dignity in the face of communist oppression.
> Added Two books and some modification in 

- README.md
* The book I am adding is "Bird by Bird" by Anne Lamott.
* I am adding this book to writing section.
* I think this book deserves to be in this list because it is written in a humorous way that makes the writing advice memorable. Lamott's stories also convey wonderful advice that is relatable.
> Adding Bird by Bird

- README.md
- [ Yes]  I am adding a new book.
* The book I am adding is "Nail it then Scale it" by Nathan Furr.
* I am adding this book to Startups and Buisness section.
* I think this book deserves to be in this list because this was my first entrepreneurial read, and I'm glad it was. The insights here are priceless if you plan on starting a company or working for a startup. It has good examples and outline about how to deal with the tech and market risks involved in ideas. I believe this process could make or break a company.
> Added a book Nail it then Scale it

- README.md
* The book I am adding is Deep Work By Cal Newport
* I am adding this book to the Education section.
* I think this book deserves to be in this list because it highlights the necessity of such an underrated skill
> Added Deep work by Cal Newport to Education

- utils/update_json_files.py
> Use openlibrary api when goodreads returns nophoto

- README.md
* The book I am adding is "The time machine" by H.G Wells
* I think this book deserves to be in this list because it has a different perspective towards time travel. Most time travel stories show flying cars and tall buildings but in this the writer shows a different perspective where humans start living peacefully and in harmony in the distant future and perspective of the time traveler who observes all these changes in the human race.
> added new science fiction book

- README.md
Im a updating publish year of book in Classic fiction section
> updated Publish year of Classic fiction

- app/src/components/bookcard.js
Image elements in Card.Img component do not have [alt] attributes. Informative elements should aim for short, descriptive alternate text.
> Add alt attribute to Card.Img component

- README.md
- utils/README.MD
* The book I am adding is "The girl with the dragon tattoo" by Stieg Larsson
* I am adding this book to mystery section.
* I think this book deserves to be in this list because the characters are very unique in this book and I fell in love with them when I read it for the first time. The plot is also very intriguing and the mystery of the main story is maintained till the end.
> added new mystery book

- README.md
some of the year ofpublications were not in the table. that has been updated
**If you are adding more than 1 category duplicate this section**
* The …
> updated year of publication

- README.md
* The book I am adding is The Turn of the Key
* I am adding this book to Mystery section.
* I think this book deserves to be in this list because it is highly-rated, thrilling, and well written. I thoroughly enjoyed this novel. It kept me on the edge of my seat and I finished it in one sitting. The book had twists, and the ending was unpredictable, emotionally-charged, and entertaining. Everything I want out of a Mystery novel.
* The book I am adding is 11/22/63
* I think this book deserves to be in this list because it is excellent. The plot pacing is on point and the characters are well-developed; you really get emotionally invested in them and the decisions they make. …
> Adding 2 new books

- README.md
The Gene: An Intimate History by Siddhartha Mukherjee. 4.35 on Goodreads! A brilliant book that takes fascinating historical, social and scientific perspectives on genetics. Mukherjee discusses his own journey dealing with his family's genetics for Schizophrenia alongside the science he presents. This book is nothing if not mind expanding.
* The book I am adding is The Gene: An Intimate History.
* I am adding this book to the Science and Medicine section.
* I have read this book 2 times. Once as an excellent Audible audiobook.
* I think this book deserves to be in this list because it takes fascinating historical, social and scientific perspectives on genetics. Mukherjee discusses his own journey dealing with his family's genetics for Schizophrenia alongside the science he presents. This …
> added a book under Science and Medicine

- README.md
* The book I am adding is Cemetery Boys
* I am adding this book to Gender section.
* I think this book deserves to be in this list because the main character is a trans latinx man who is navigating his relationship with his family (in relation to his transition) BUT there are ghosts. I mean, sci-fi, trans-rights, traditional latinx family dynamics..no brainer. A must read!
* The book I am adding is Becoming a Man
* I am adding this book to Gender section.
* I think this book deserves to be in this list because it is an autobiographical account of one man's experience transitioning later in life. It's really insightful and is a great read. 
* The book I am adding is Paul Takes the Form of a Mortal Girl
* I am adding this book …
> adding cemetery boys, becoming a man, and paul takes the form of a mortal girl

- README.md
* The book I am adding is Brave New World by Aldous Huxley
* I think this book deserves to be in this list because it was way ahead of its time. First published in 1932, it discusses a world where government has complete control of everyone's life including how they are even born! The book discusses many things including the use of drugs, human sexuality, and pleasure to control people. It also discusses the beauty of tradition in a society that is more accustomed to …
> Added Brave New World by Aldous Huxley

- README.md
* The book I am adding is  "The Kite Runner"
* I am adding this book to the "Historical Fiction" section.
* I have read this book "one" time.
* I think this book deserves to be on this list because it's a great historical fiction based on Afghanistan's past and gives a new perspective to do the right things at right time.
> Add The Kite Runner by Khaled Hosseini

- README.md
* The book I am adding is Siddhartha by Hermann Hesse
* I am adding this book to Classics section.
* I have read this book  1 times.
* I think this book deserves to be in this list because it is a profound story of one mans journey but also about life itself with its ups and downs
> about one mans journey to enlightenment but also about life itself

- app/src/components/bookcard.js
The pictures were really pixelated  and there was a lot of scrolling to be done on mobile so I changed their width to make it was a bit better. I also added a small screen size instead of it just going from xs to md.
> edit for mobile and small screen readability

- README.md
* The book I am adding is Autobiography of a Yogi
* I am adding this book to Autobiographies and Biographies section.
* I think this book deserves to be in this list because it is a classical autobiography of an Indian Monk who describes his entire his life around ancient Indian Spiritual masters when he grew and the spiritual miracles he encountered in his life from the revered spiritual masters he visited.Moreover,he also shares 3 simple meditation methods for mental and spiritual well-being.
**If you are adding more …
> Added a book "Autobiography of a Yogi"

- README.md
* The book I am adding is Profiles of the Future: An Inquiry into the Limits of the Possible 
* I am adding this book to the Science section.
* I think this book deserves to be in this list because it warns us not to make similar mistakes in the future by evaluating the past very well in terms of science.
> [Profiles of the Future by Arthur C. Clarke] I am adding a new book.

- README.md
* The book I am adding is AI Superpowers: China, Silicon Valley, and the New World Order by Kai-Fu Lee
* I think this book deserves to be in this list because it presents a current and futuristic view on the impact of artificial intelligence applications in several areas ranging from the business, governmental and everyday life.
> Add "AI Superpowers" to Startups and Business

- README.md
* The book I am adding is 'Memoirs of a Geisha'.
* I am adding this book to 'Historical Fiction' section.
* I think this book deserves to be in this list because this brilliant novel presents the true confessions of one of Japan's most celebrated geisha.
>  Added 'Memoirs of a Geisha' book on the 'Historical Fiction' section. 

- README.md
* The book I am adding is **Data Driven**
* I am adding this book to **Startups and Business** section.
* I have read this book **1** time.
* I think this book deserves to be in this list because: D.J. Patil is the author that coined the term "Data Science". In this book he introduces for the first time in startup and technology business the Data Driven concept.
> adding data driven

- CONTRIBUTING.md
Hey there.
i just fixed a simple typographical error in CONTRIBUTING.md
> Fix typo error in  CONTRIBUTING.md

- README.md
* The book I am adding is "The Innovators" by Walter Isaacson
* I am adding this book to the Autobiography and Biography section.
* I think this book deserves to be in this list because it counters the prevailing narrative that tech is the space of single visionaries, and shines a light on the teamwork that made foundational hardware, software, and practices possible. It also has an interesting foray into the concept of open-source, which seems topical for Hacktoberfest.
> Add "The Innovators" to Autobiography and Biography

- README.md
* The book I am adding is "Data visualization handbook" by Juuso Koponen & Jonatan Hildén
* I am adding this book to Design section.
* I have read this book multiple times.
* I think this book deserves to be in this list because it's an amazingly comprehensive resource for data visualisation and a book that I reference constantly in my work as a graphic designer.
> Added "Data visualization handbook" to Design

- README.md
* The book I am adding is "Outnumbered: Exploring the Algorithms That Control Our Lives" by David Sumpter.
* I am adding this book to Logic and Problem Solving section.
* I think this book deserves to be in this list because it relates to very current topics of how mathematics and statistics can influence our daily choices. Author is a mathematician and explains on a very high level how various algorithms work. The concepts can be easily understood even by readers without deeper education in mathematics.
> Add "Outnumbered" to Logic and Problem Solving

- README.md
- app/src/data/books.json
- app/src/data/categories.json
* The book I am adding is Drawing on the right side of the brain
* I am adding this book to Art section.
* I think this book deserves to be in this list because it has a very special way of destroying the prejudice that one needs some incredible talent to be a good artist / painter. However, calling it just a book about art would be underselling it - the book has a lot on how we thing, how we perceive and many other psychological aspects of a human character that can make us put ourselves in proverbial boxes without realizing hidden talents we might have.
* The book I am adding is Steal like an artist
* I am adding this book to Art section.
* I have read this book 4 times.
* I think this book deserves to be in this list because it helped me grow further in …
> Adds art as a category; Adds three book to art category;

- README.md
* The book I am adding is "Bad Blood: Secrets and Lies in a Silicon Valley Startup" .
* I am adding this book to startup and buisness section.
* I think this book deserves to be in this list because it is so great and thrilling. I have read this book twice and both times could not put it down. It amazes me that one person can deceive so many. It is completely unbelievable what they got away with for so long! 
* The reason …
> Added book in Startup and Buisness section.

- README.md
* The book I am adding is Everything Beautiful in Its Time: Seasons of Love and Loss by Jenna Bush Hager
* I am adding this book to Autobiographies and Biographies section.
* I have read this book two times.
* I think this book deserves to be in this list because Everything Beautiful in Its Time is a warm and wonderful celebration of the enduring power of family and an exploration of the things that truly matter most. This is a very good book written by New York Times bestselling author #1 :)
> Include everything beautiful by Jenna Bush Hager

- README.md
* The book I am adding is "=Rosemary's Baby" .
* I am adding this book to horror fiction section.
* I think this book deserves to be in this list because this book just isn't the same without the accompanying film though, the vibrant bright colors of celluloid film and the excellent acting and soundtrack were what brought this story to life. 
* The book I am adding is "If it bleeds" .
* I am adding this book to horror fiction section.
* I think this book deserves to be in this list because …
> Added two horror fiction books.

- README.md
* The book I am adding is Thus Spoke Zarathustra
* I am adding this book to Philosophy And Psychology section.
* I have read this book 5 times.
* I think this book deserves to be in this list because this is one of my favorite books in general, and definitely my favorite philosophy book. I've read and re-read this book at pivotal moments in my life. Nietzsche is one of the first to spread the philosophy of "God is dead!" that now resembles Satanic beliefs, and is still a widely read book amongst Nihilists of all flavors. This book is not merely a critique on Christianity and organized religion; it is a manifesto of free will that people still read to this day. I highly recommend it as a mind-expanding book.
> Add Thus Spoke Zarathustra

- README.md
* The book I am adding is The Disappearing Spoon: And Other True Tales of Madness, Love, and the History of the World from the Periodic Table of the Elements
* I am adding this book to Science and Medicine
* I think this book deserves to be in this list because it clearly explains the discovery and applications of elements from periodic table through history.
> Added the book The Disappearing Spoon

- README.md
* The book I am adding is "The Wild Places".
* I am adding this book to nature's section.
* I think this book deserves to be in this list because the themes that flow through MacFarlane’s writing – friendship, life, death, the past, present and future of our species and our relationship with our surroundings – feel like a layered extension of the landscapes he observes so keenly. They ebb and flow through the chapters as much (and in much the same way) as the weather, seasons, water, and migrating birds he describes
**If …
> Added book to nature section.

- README.md
sometimes a thought comes in mind to give up everything, there is so much attachment and suffering in this world. so should one leave everything a become a Sadhu? one should not move away from his responsibilities and one doesn't have to become the sadhu to get the peace. one can find peace in most noisy place in universe and in utmost silence. the book is somewhat different from normal self- help books.  it tells to not be attached to the work  which you are doing. 
it nicely explains the concept of religion and karma, work, why one needs to do the karma.
I feel this is the best book i have ever read.
If you are unsure, please check other PRs like this one: …
> Added a new Book ' Karma Yoga' by Swami Vivekanand

- README.md
* The book I am adding is The Middle Finger Project
* I think this book deserves to be in this list because it is smart, funny and absurdly relevant, especially for women who are interested in creating their own business.
> add the middle finger project

- README.md
* The book I am adding is "The Body: A Guide for Occupants" by Bill Bryson
* I am adding this book to Science and Medicine section.
* I have read this book two times.
* I think this book deserves to be on this list because it allows you to better appreciate what you are and how you work.
> add "The Body" by Bill Bryson

- README.md
* The book I am adding is "A Walk in the Woods".
* I am adding this book to Nature's section.
* I think this book deserves to be in this list because definitely read the book if you're a fan of the outdoors and hiking. It was amazing.
**If you are adding more than 1 category duplicate this …
> Added book in nature's section.

- README.md
* The book I am adding is "The Origin of Others".
* I am adding this book to race section.
* I think this book deserves to be in this list because it felt like Morrison could have gone a little deeper. Maybe it's only meant to serve as an intro to her works, as opposed to fully-fleshed out analytical essays. Worth reading!
* - [ ] I have added at …
> Added book to Race

- README.md
**If you are adding more than 1 category duplicate this section**
* The book I am removing is _ _ _ _
* I am removing this book from _ _ _ _ section.
* …
> added Factfulness

- README.md
**If you are adding more than 1 category duplicate this section**
* The book I am removing is _ _ _ _
* I am removing this book from _ _ _ _ section.
* …
> added Slaughterhouse-Five by Kurt Vonnegut

- README.md
> Fix goodreads link for Educated

- README.md
> Updating README -> Startups and Business Goodreads ratings

- README.md
* The book I am adding is *The Uninhabitable Earth: Life After Warming*.
* I am adding this book to the *Nature* section.
* I have read this book *1.5* times.
* I think this book deserves to be in this list because *it illustrates how climate change will affect our planet, lives and everything in-between in the future (and how it already has). It shows that this isn't just about rising sea levels and is, in my opinion, one of the most important books out there right now.*
> Add The Uninhabitable Earth by David Wallace-Wells

- utils/books.json
Fix: #371
##Book name:
- The Discoverers by Daniel J. Boorstin
- Removed the jpg file of wrong book cover
- Replaced it with correct book cover's jpg link
> Update for book cover of "The Discoverers"

- README.md
* The book I am adding is The Ascent of Humanity by Charles Eisenstein
* I am adding this book to the Philosophy and Psychology section.
* I think this book deserves to be in this list because it can give the reader a new broad vision of life, and it's also highly rated.
> Add "The Ascent of Humanity", by Charles Eisenstein.md

- README.md
> fixing bad markdown in link

- README.md
* The book I am adding is  Grain Brain: The Surprising Truth about Wheat, Carbs, and Sugar--Your Brain's Silent Killers 
* I am adding this book to health section.
* I think this book deserves to be in this list because you learn a lot about optimising your brain health. You can use this knowledge to improve yourself as a developer.
> Add Grain Brain health book

- README.md
* The book I am adding is "Prodigy" by Marie Lu 
* I am adding this book to the Science Fiction section.
* I think this book deserves to be in this list because I find this book to be very captivating. The author does a really good job portraying the characters' stories and motives throughout the novel. The ongoing suspense throughout the book makes it a fun read.
> Added Prodigy to Science Fiction

- README.md
> this commit fixes  Small typo #419

- README.md
* The book I am adding is Principles: Life and Work by Ray Dalio
* I am adding this book to Philosophy And Psychology section.
* I think this book deserves to be in this list because it demonstrates a way of leading a life based on personal values, designed by yourself and for yourself. By being truthful and honest with himself, answering questions about what he wanted out of life, the author demonstrates the path he took to reach his truth.
> Add "Principles: Life and Work" by "Ray Dalio"

- README.md
The book is a journey that tries to portray a healthy, creative and effective business culture. Based on real examples from companies like Pixar or Apple. A delight to put into practice in any company, large, small or teams.
* The book I am adding is Creativity Inc
* I think this book deserves to be in this list because you can put it on practice to improve many different aspects of your company or teams.
**If you are adding more than 1 books duplicate this …
> Creativity Inc book added

- README.md
> Varadrane7 added back to top

- README.md
* The book I am adding is Leo Brodie's "Thinking Forth: A Language and Philosophy for Solving Problems"
* I am adding this book to the Logic and Problem Solving section.
* I think this book deserves to be in this list because It has fundamentally changed the way I think about and approach problems; not only in computer programming, but also in life. The FORTH programming language and it's associated
philosophy is a great paradigm shift, and the techniques of factoring problems in this way can be effectively applied
throughout one's workflows. The friendly, humorous tone makes this text far more readable than many other texts on
computer science. I believe it to be a must read for any programmer, and I highly recommend it to non-programmers.
> Add Thinking Forth

- README.md
* The book I am adding is The Daily Stoic
* I am adding this book to  Philosphy and Psychology section.
* I think this book deserves to be in this list because it is a beautifully packaged daily devotional of Stoic wisdom, featuring new translations of the most celebrated Stoics with historical context and practical tips from bestselling author Ryan Holiday.
* The reason why I think this category should be there is because …
> Added The Daily Stoic

- README.md
Added The Soul of a New Machine to the history section.
* The book I am adding is The Soul of a New Machine.
* I am adding this book to the History section (It could also go in Science & Medicine but I think History is a better fit).
* I think this book deserves to be in this list because it tells the interesting and sometimes harrowing tale of creating a new computer. Creating this machine behind the backs of the higher ups in the company and while engineering a cutting edge personal computer.
> Added The Soul of a New Machine

- README.md
* The book I am adding is Contact by Carl Sagan
* I am adding this book to the Science Fiction section.
* I think this book deserves to be on this list because it is an extremely well-written work by the scientific genius Carl Sagan about mankind stumbling upon contact with extraterrestrial beings and how it affects humanity as a whole.
> Added Contact to the list of science fiction books

- README.md
* The book I am adding is "Breath: The New Science of a Lost Art" by James Nestor
* I am adding this book to Health section.
* I think this book deserves to be in this list because it is incredibly well written and a well respected entry on the science of breathing properly and how it affects our health.
> Added "Breath: The New Science of a Lost Art" to Health

- README.md
* The book I am adding is "Project Hail Mary" by Andy Weir
* I am adding this book to the Science Fiction section.
* I think this book deserves to be in this list because it's my current favorite science fiction book, and when I recommended it to my sister, she binged it and said it's her new favorite as well. Andy Weir's previous book "The Martian" is already on the list, and his adventurous writing style has only improved since then.
> Added Project Hail Mary to Science Fiction

- README.md
* The book I am adding is Angels & Demons by Dan Brown
* I am adding this book to Mystery section.
* I think this book deserves to be in this list because its a magnificent example of a mystery book, you'll be always catch in the story
**If you are adding more than 1 category duplicate this …
> Added a new book, Angels & Demons by Dan Brown

- README.md
* The book I am adding is "London(Surviving The Evacuation-Book One)"  by Frank Tayell.
* I am adding this book to the Fiction section, the Horror sub-category.
* I have read this book two times.
* I think this book deserves to be in this list because it describes the main character's determination to survive an apocalypse even though he was stuck in a wheelchair at the beginning of the apocalypse. It is a well written book.
> Adding "London(Surviving The Evacuation #1)" to the Fiction category

- README.md
* The book I am adding is "The Way of the Monk"
* I am adding this book to "Philosophy And Psychology" section.
* I think this book deserves to be in this list because it can help people search the purpose of their life, and move on with their lives
> Added "The Way of the Monk"

- README.md
Life of this man is an outright expression of leadership, success and Indian ethos. A must read for all budding professionals.
* - [x] I have added at least one book to this category 
**If you are adding more …
> Added Man without Fear by Rajat Gupta

- README.md
* The book I am adding is "Crucial Conversations" by Kerry Patterson
* I am adding this book to the Startups and Business section.
* I think this book deserves to be in this list because it helps in those challenging situations where we are having difficult conversations. This book helps us to stay focused on what really matters to us, and how effective communication is a key to getting there faster.
> feat: Add Crucial Conversations book

- README.md
* The book I am adding is "The Millionaire Fastlane: Crack the Code to Wealth and Live Rich for a Lifetime!" by M.J. DeMarco.
* I am adding this book to the Startups and Business section.
* I think this book deserves to be in this list because it compares the slow and fast lanes of business techniques that one can learn from.
> Add "The Millionaire Fastlane" to Startups and Business

- README.md
Adding new book
* The book I am adding is Of Fire and Stars
* I am adding this book to Fantasy section.
* I have read this book  3 times.
* I think this book deserves to be in this list because i love this book and is a lgbt+ book
> add book: Of Fire and Stars

- README.md
* The book I am adding is The Magic of Thinking Big.
* I am adding this book to Philosophy and Psychology section.
* I have read this book 1 time(s).
* I think this book deserves to be in this list because it motivates us to keep thinking positively and big.
> Added "The Magic of Thinking Big" book

- README.md
* The book I am adding is Change by Design: How Design Thinking Transforms Organizations and Inspires Innovation 
* I am adding this book to Design section.
* I think this book deserves to be in this list because it inspire to transforms organizations and develop innovation by design thinking
* - [ ] I have added at least one book to this category …
> Added new design book

- README.md
* The books I am adding are:
1. The Almanack of Naval Ravikant: A Guide to Wealth and Happiness by Eric Jorgenson
2. Bloodlands: Europe Between Hitler and Stalin by Timothy Snyder 
3. On Tyranny: Twenty Lessons from the Twentieth Century by Timothy Snyder
* I am adding this book to sections:
1. Philosophy And Psychology
2. History
3. Politics
* I have read these books one time from cover to cover. And returned to read certain chapters multiple times :)
* I think these books deserves to be in this list because:
1. [Naval Ravikant](https://twitter.com/naval) went from a poor kid to a millionaire. He talks a lot about (creating) wealth and philosophy of life.
2. People usually know what happened during 1940s in Europe, but what happened in Ukraine before isn't that known. You'll be horrified …
> Add books by Jorgenson and Snyder

- README.md
* The book I am adding is The Age of Em: Work, Love and Life When Robots Rule the Earth 
* I am adding this book to Philosophy and Psychology section.
* I think this book deserves to be in this list because it is a rare entry into the genre of academic speculative history. The economist Robin Hanson explores how our world would look like in the future if full brain emulation would become a reality. He goes into many details such a city planing of huge computing centers or the personal lifes of simulated persons.
> Added The Age of Em

- README.md
* The book I am adding is _A Sense of the World_ by Jason Roberts
* I am adding this book to the Autobiographies and Biographies section.
* I have read this book two times 
* I highly suggest adding "A Sense of the World" by Jason Roberts to any list of mind-expanding books. This book tells the incredible story of James Holman, a blind man who accomplished great feats as a traveler back in the 18th and 19th centuries. Despite his blindness, Holman relied on his other senses and the kindness of locals to navigate the world. The book provides a unique perspective on travel and exploration that is inspiring and remarkable. It has received critical acclaim and has been named a Best Book of the Year by numerous publications, making it a well-respected work. Overall, "A Sense of the World" is a …
> Adding book into the Autobiography and biographies section

- README.md
* from 'Ryan Holding' to 'Ryan Holiday'.
> corrected 'Ryan Holding' to 'Ryan Holiday'

- README.md
* The book I am adding is **Limitless**
* I am adding this book to **Education** section.
* I have read this book **3** times.
* I think this book deserves to be on this list because the author was a kid with a broken brain, but he made himself a brain coach. In this book, the author helps readers to become limitless by mastering their habits, unleashing productivity, having boundless motivation, sharpening focus, and learning anything quickly. After reading this book, I have improved my life vastly be it motivation, improving my grades in study.
* The book I am adding is **Brain Food**
* I am adding this book to **Health** section.
* I have read this book **1** time.
* I think this book deserves to be on this list because the author lays out a complete understanding of neuro-nutrition …
> added 'Limitless', 'Brain Food' and 'Super Human' in README

- CONTRIBUTING.md
I am not adding a book, I fixed the grammar mistakes in CONTRIBUTING.md.
> Spelling and grammar in CONTRIBUTING.md
